name: Matrix-workflow
on:
    push:
        branches:
            - master
jobs:
    test:
        continue-on-error: true
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node: [12, 16, 18]
                include:
                   - os: windows-latest
                     node: 12
                   - os: ubuntu-latest
                     node: 16
                exclude:
                    - os: macos-latest
                      node: 12

        runs-on: ${{ matrix.os}}
        steps:
          - name: download code
            uses: actions/checkout@v3
          - name: install dependency
            uses: actions/setup-node@v3
            with:
                node-version: ${{ matrix.node}}
            