name: Matrix-workflow
on:
    push:
        branches:
            - master
jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node: [16, 18]
        runs-on: ${{ matrix.os}}
        steps:
          - name: download code
            uses: actions/checkout@v3
          - name: install dependency
            uses: actions/setup-node@v3
            with:
                node-version: ${{ matrix.node}}
            