name: Reusable_call
on: 
    workflow_call:
        inputs:
            artifact-name:
                required: true
                type: string
                description: "Name of the artifact to upload"
                default: dist 

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Download code
              uses: actions/checkout@v3
              with:
                name: ${{ inputs.artifact-name }}
            - name: list files
              run: ls
            - name: Output info
              run: echo "This is a reusable workflow"